# Welcome to the Jungle! (of packages)

![Axl](https://cdn-0.gnrcentral.com/wp-content/uploads/2018/12/slash-axl-rose-guns-n-roses-800x420.jpg)


## Numpy

Numpy is a package that allows us to perform certain numerical operations that are not available in native python. 

In [1]:
import numpy as np

## Array

In [2]:
#remember lists?

list1=[1,2,3,4]

list2=[5,6,7,8]


In [3]:
list1+list2

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
#let's turn them into arrays

array1=np.array(list1)
array2=np.array(list2)

In [5]:
array1

array([1, 2, 3, 4])

In [6]:
array1+array2

array([ 6,  8, 10, 12])

In [7]:
array1*array2

array([ 5, 12, 21, 32])

In [8]:
array1*2

array([2, 4, 6, 8])

In [9]:
array1+np.array([2,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [10]:
#Size of the array

len(array1)

4

In [11]:
array1.shape

(4,)

In [12]:
array1=array1.reshape(4,1)
array1.shape

(4, 1)

In [13]:
array1

array([[1],
       [2],
       [3],
       [4]])

In [14]:
arrZeros = np.zeros((2,3))
arrZeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arrOnes = np.ones((2,2)) 
arrOnes

array([[1., 1.],
       [1., 1.]])

In [16]:
arrEyes = np.eye(3)  
arrEyes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Transposition

arrZeros.shape

(2, 3)

In [18]:
arrZeros.T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
arrZeros.T.shape

(3, 2)

In [20]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
#Broadcasting

array1+2

array([[3],
       [4],
       [5],
       [6]])

**Exercises.** Initialize a 4 by 1 array with 2 and named it as arrE1.

**Exercises.** Initialize a 1 by 4 array with number 3 and named it as arrE2.

**Exercises.** Can you perform an element wise add operation of the arrE1 and arrE2?



In [25]:
arrE1=np.ones((4,1))*2
print(arrE1)

arrE2=arrE1.T+1
print(arrE2)

[[2.]
 [2.]
 [2.]
 [2.]]
[[3. 3. 3. 3.]]


In [28]:
arrE1+arrE2

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

**Exercises (challenging).** How to create a 3 by 3 array with only zeros in diagonal while the rest is 2?

In [31]:
(np.ones((3,3))-np.eye(3))*2

array([[0., 2., 2.],
       [2., 0., 2.],
       [2., 2., 0.]])

In [32]:
arrE1= np.ones((4,1))+np.ones((4,1))
arrE1

array([[2.],
       [2.],
       [2.],
       [2.]])

In [33]:
arrE2=np.ones((1,4))*3
arrE2

array([[3., 3., 3., 3.]])

In [34]:
prearray=np.ones((3,3))-np.eye(3)
prearray*2

array([[0., 2., 2.],
       [2., 0., 2.],
       [2., 2., 0.]])

## Slicing

In [35]:
newarray=np.array([[5,12,31],[2,7,11],[15,21,32]])
newarray

array([[ 5, 12, 31],
       [ 2,  7, 11],
       [15, 21, 32]])

In [36]:
#what will this return?

newarray[2,2]

32

In [37]:
newarray[1, :]

array([ 2,  7, 11])

In [38]:
newarray[,2]

SyntaxError: invalid syntax (<ipython-input-38-759ffe6d4f3e>, line 1)

In [39]:
newarray[:,2]

array([31, 11, 32])

In [40]:
newarray[:,2].shape

(3,)

In [41]:
newarray[0,0:2]

array([ 5, 12])

### Elementwise Methods (can use on floats)


In [42]:
#natural logarithm
np.log(array1)

array([[0.        ],
       [0.69314718],
       [1.09861229],
       [1.38629436]])

In [43]:
np.log(2)

0.6931471805599453

In [44]:
# Euler constant

np.exp(array1)

array([[ 2.71828183],
       [ 7.3890561 ],
       [20.08553692],
       [54.59815003]])

In [45]:
# square root

np.sqrt(array1)

array([[1.        ],
       [1.41421356],
       [1.73205081],
       [2.        ]])

## Array wise operations

In [46]:
newarray

array([[ 5, 12, 31],
       [ 2,  7, 11],
       [15, 21, 32]])

In [47]:
np.sum(newarray)

136

In [48]:
# Column wise
np.sum(newarray, axis=0)

array([22, 40, 74])

In [49]:
#row wise
np.sum(newarray, axis=1)

array([48, 20, 68])

In [50]:
#number of rows
newarray.shape[0]

3

In [51]:
#number of columns

newarray.shape[1]

3

Exercises. How to compute the column mean?

Exercises. How to compute the column mean in second and third column?

Exercises. How to compute the row mean?

In [52]:
np.sum(newarray, axis=0)/newarray.shape[0]

array([ 7.33333333, 13.33333333, 24.66666667])

In [53]:
np.sum(newarray[:,1:3], axis=0)/newarray.shape[0]

array([13.33333333, 24.66666667])

## Random number generator

In [54]:
np.random.randn(2,4)


array([[ 0.15972621, -0.62398761, -0.64628491, -1.11236542],
       [ 1.46783933,  0.84048466,  0.43918748,  0.95306136]])

# PANDAS

In [55]:
import pandas as pd

In [56]:
newdf=pd.DataFrame(newarray)
newdf

0   1   2
0   5  12  31
1   2   7  11
2  15  21  32

In [57]:
#Slicing dataframes

newdf.iloc[:,1:]

1   2
0  12  31
1   7  11
2  21  32

In [58]:
newdicto= {"Name":['Carlos', 'Paul', 'Xuan'], 'Age':[23,32,15], 'OS':['Windows','OSX', 'Windows']}

In [59]:
newdicto

{'Name': ['Carlos', 'Paul', 'Xuan'],
 'Age': [23, 32, 15],
 'OS': ['Windows', 'OSX', 'Windows']}

In [60]:
newdf=pd.DataFrame(newdicto)

newdf

Name  Age       OS
0  Carlos   23  Windows
1    Paul   32      OSX
2    Xuan   15  Windows

In [61]:
newdf['Age']

0    23
1    32
2    15
Name: Age, dtype: int64

In [62]:
np.mean(newdf['Age'])

23.333333333333332

In [63]:
newdf.iloc[:,1]

0    23
1    32
2    15
Name: Age, dtype: int64

In [64]:
newdf['OS'].unique()

array(['Windows', 'OSX'], dtype=object)